# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#

---
include:
  - board: nice_nano_v2
    shield: settings_reset
  - board: skean_left
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Skean_MX\"
    artifact-name: skean_mx_left
  - board: skean_right
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Skean_MX\"
    artifact-name: skean_mx_right
  - board: skean_left
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Skean_LP\"
    artifact-name: skean_mx_left
  - board: skean_right
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Skean_LP\"
    artifact-name: skean_mx_right
